<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\common\Lib.Shared.DataModels\Lib.Shared.DataModels.csproj" />
    <ProjectReference Include="..\..\common\Lib.Shared.Abstractions\Lib.Shared.Abstractions.csproj" />
    <ProjectReference Include="..\..\Lib.Adapters\Lib.Adapter.Scryfall.Cosmos\Lib.Adapter.Scryfall.Cosmos.csproj" />
    <ProjectReference Include="..\..\core\Lib.Cosmos\Lib.Cosmos.csproj" />
    <ProjectReference Include="..\..\common\Lib.Shared.Invocation\Lib.Shared.Invocation.csproj" />
    <ProjectReference Include="..\..\core\Lib.Universal\Lib.Universal.csproj" />
    <ProjectReference Include="..\Lib.Aggregator.Scryfall.Shared\Lib.Aggregator.Scryfall.Shared.csproj" />
    <ProjectReference Include="..\..\Lib.Adapters\Lib.Adapter.Cards\Lib.Adapter.Cards.csproj" />
  </ItemGroup>

</Project>
