<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Cli.MtgDiscovery.DataMigration\Cli.MtgDiscovery.DataMigration.csproj" />
    <ProjectReference Include="..\TestConvenience.Core\TestConvenience.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
