###
# Add Card To Collection Mutation
# Frontend: client/src/graphql/mutations/addCardToCollection.ts - ADD_CARD_TO_COLLECTION
# NOTE: This mutation requires JWT authentication header
###
@baseUrl = https://localhost:65203
@gqlEndpoint = {{baseUrl}}/graphql


### Add Card to Collection
POST {{gqlEndpoint}}
Content-Type: application/json
Authorization: Bearer {{BEARER_TOKEN}}

mutation AddCardToCollection($args: AddCardToCollectionInput!) {
  addCardToCollection(args: $args) {
    __typename
    ... on CardsSuccessResponse {
      data {
        id
        name
        setCode
        setName
        collectorNumber
        rarity
        artist
        userCollection {
          finish
          special
          count
        }
      }
    }
    ... on FailureResponse {
      __typename
      status {
        message
        statusCode
      }
    }
  }
}

{
  "args": {
    "cardId": "0223cf7f-4c6e-487f-babb-a740a15e1f0c",
    "setId": "a2f58272-bba6-439d-871e-7a46686ac018",
    "userId": "6cd19505-4db6-5a83-94b5-8d58f7f8aa38",
    "userCardDetails": {
      "finish": "foil",
      "special": "none",
      "count": 2,
      "setGroupId": "draft-cards"
    }
  }
}
