###
# Variables
# @name variables
@baseUrl = {{$dotenv BASE_URL}}
@graphqlEndpoint = {{baseUrl}}/graphql


### Get All Sets
# @ref variables
POST {{graphqlEndpoint}}
Content-Type: application/json

query GetAllSets {
  allSets {
    __typename
    ... on SuccessSetsResponse {
      data {
        id
        code
        tcgPlayerId
        name
        uri
        scryfallUri
        searchUri
        releasedAt
        setType
        cardCount
        digital
        nonFoilOnly
        foilOnly
        block
        iconSvgUri
      }
    }
    ... on FailureResponse {
      status {
        message
        statusCode
      }
    }
  }
}

{}