###
# All User Set Cards Query Tests
# Queries for all set collection statistics for a specific user
# Shows aggregated data across all sets for a user

###
# Variables
# @name variables
@baseUrl = https://localhost:65203
@graphqlEndpoint = {{baseUrl}}/graphql

### Get All User Set Cards
# @ref variables
# Get aggregated statistics for all sets in a user's collection
POST {{graphqlEndpoint}}
Content-Type: application/json

query GetAllUserSetCards($userSetCardsArgs: AllUserSetCardsInput!) {
  allUserSetCards(userSetCardsArgs: $userSetCardsArgs) {
    __typename
    ... on AllUserSetCardsSuccessResponse {
      data {
        userId
        setId
        totalCards
        uniqueCards
        collecting {
          setGroupId
          collecting
          count
        }
        groups {
          rarity
          group {
            nonFoil {
              cards
            }
            foil {
              cards
            }
            etched {
              cards
            }
          }
        }
      }
      status {
        message
        statusCode
      }
    }
    ... on FailureResponse {
      status {
        message
        statusCode
      }
    }
  }
}

{
  "userSetCardsArgs": {
    "userId": "6cd19505-4db6-5a83-94b5-8d58f7f8aa38"
  }
}
