###
# Variables
# @name variables
@baseUrl = {{$dotenv BASE_URL}}
@cardEndpoint = {{baseUrl}}/graphql


### Search Cards by Name - Short search term
# @ref variables
POST {{cardEndpoint}}
Content-Type: application/json

query CardNameSearch($searchTerm: CardSearchTermArgEntityInput!) {
  cardNameSearch(searchTerm: $searchTerm) {
    __typename
    ... on SuccessCardNameSearchResultsResponse {
      data {
        name
      }
    }
    ... on FailureResponse {
      status {
        message
      }
    }
  }
}

{
  "searchTerm": {
    "searchTerm": "bolt"
  }
}

### Search Cards by Name - Long search term
# @ref variables
POST {{cardEndpoint}}
Content-Type: application/json

query CardNameSearch($searchTerm: CardSearchTermArgEntityInput!) {
  cardNameSearch(searchTerm: $searchTerm) {
    __typename
    ... on SuccessCardNameSearchResultsResponse {
      data {
        name
      }
    }
    ... on FailureResponse {
      status {
        message
      }
    }
  }
}

{
  "searchTerm": {
    "searchTerm": "asmoranomardicadaistinaculdacar"
  }
}

### Search Cards by Name - With spaces
# @ref variables
POST {{cardEndpoint}}
Content-Type: application/json

query CardNameSearch($searchTerm: CardSearchTermArgEntityInput!) {
  cardNameSearch(searchTerm: $searchTerm) {
    __typename
    ... on SuccessCardNameSearchResultsResponse {
      data {
        name
      }
    }
    ... on FailureResponse {
      status {
        message
      }
    }
  }
}

{
  "searchTerm": {
    "searchTerm": "n mino"
  }
}
}

### Search Cards by Name - With spaces
# @ref variables
POST {{cardEndpoint}}
Content-Type: application/json

query CardNameSearch($searchTerm: CardSearchTermArgEntityInput!) {
  cardNameSearch(searchTerm: $searchTerm) {
    __typename
    ... on SuccessCardNameSearchResultsResponse {
      data {
        name
      }
    }
    ... on FailureResponse {
      status {
        message
      }
    }
  }
}

{
  "searchTerm": {
    "searchTerm": "mino"
  }
}

### Search Cards by Name - Partial word
# @ref variables
POST {{cardEndpoint}}
Content-Type: application/json

query CardNameSearch($searchTerm: CardSearchTermArgEntityInput!) {
  cardNameSearch(searchTerm: $searchTerm) {
    __typename
    ... on SuccessCardNameSearchResultsResponse {
      data {
        name
      }
    }
    ... on FailureResponse {
      status {
        message
      }
    }
  }
}

{
  "searchTerm": {
    "searchTerm": "ghtni"
  }
}

### Search Cards by Name - Too short (should fail)
# @ref variables
POST {{cardEndpoint}}
Content-Type: application/json

query CardNameSearch($searchTerm: CardSearchTermArgEntityInput!) {
  cardNameSearch(searchTerm: $searchTerm) {
    __typename
    ... on SuccessCardNameSearchResultsResponse {
      data {
        name
      }
    }
    ... on FailureResponse {
      status {
        message
        statusCode
      }
    }
  }
}

{
  "searchTerm": {
    "searchTerm": "ab"
  }
}