###
# Get Cards By IDs Query
# Frontend: client/src/graphql/queries/cards.ts - GET_CARDS_BY_IDS
###
@baseUrl = https://localhost:65203
@gqlEndpoint = {{baseUrl}}/graphql


### Get Cards Batch by IDs
POST {{gqlEndpoint}}
Content-Type: application/json

query GetCardsBatch($ids: CardIdsArgEntityInput!) {
  cardsById(ids: $ids) {
    __typename
    ... on CardsSuccessResponse {
      data {
        id
        oracleId
        name
        lang
        releasedAt
        uri
        scryfallUri
        layout
        highResImage
        imageStatus
        imageUris {
          small
          normal
          large
          png
          artCrop
          borderCrop
        }
        manaCost
        cmc
        typeLine
        oracleText
        power
        toughness
        colors
        colorIdentity
        keywords
        setId
        setCode
        setName
        setType
        collectorNumber
        digital
        rarity
        artist
        artistIds
        illustrationId
        borderColor
        frame
        prices {
          usd
          usdFoil
          usdEtched
          eur
          eurFoil
          tix
        }
        relatedUris {
          gatherer
          tcgplayerInfiniteArticles
          tcgplayerInfiniteDecks
          edhrec
        }
        purchaseUris {
          tcgplayer
          cardmarket
          cardhoarder
        }
        userCollection {
          finish
          special
          count
        }
      }
    }
    ... on FailureResponse {
      status {
        message
      }
    }
  }
}

{
  "ids": {
    "userId": "6cd19505-4db6-5a83-94b5-8d58f7f8aa38",
    "cardIds": [
      "3e7da55a-e0ff-4475-a67f-0f493726972e",
      "b3dffe4b-45ff-4b88-a1fc-26f7e85d6cd3"
    ]
  }
}
