###
# Update Collection Mutation
# Frontend: client/src/graphql/mutations/collection.ts - UPDATE_COLLECTION
###
@baseUrl = https://localhost:65203
@gqlEndpoint = {{baseUrl}}/graphql


### Update Collection
POST {{gqlEndpoint}}
Content-Type: application/json

mutation UpdateCollection($input: UpdateCollectionInput!) {
  updateCollection(input: $input) {
    ... on SuccessCardResponse {
      __typename
      card {
        id
        name
        setCode
        setName
        collectorNumber
        rarity
        artist
        userCollection {
          finish
          special
          count
        }
      }
    }
    ... on FailureResponse {
      __typename
      status {
        message
      }
    }
  }
}

{
  "input": {
    "cardId": "3e7da55a-e0ff-4475-a67f-0f493726972e",
    "finish": "foil",
    "special": false,
    "count": 2
  }
}
