###
# Variables
# @name variables
@baseUrl = https://localhost:65203
@graphqlEndpoint = {{baseUrl}}/graphql


### Get All Sets
# @ref variables
POST {{graphqlEndpoint}}
Content-Type: application/json

query GetAllSets {
  allSets {
    __typename
    ... on SuccessDataResponseModel {
      data {
        id
        code
        name
        releasedAt
        setType
        cardCount
        digitalOnly
        foilOnly
        iconSvgUri
      }
    }
    ... on FailureResponseModel {
      status {
        message
        statusCode
      }
    }
  }
}

{}