###
# Variables
# @name variables
@baseUrl = https://localhost:65203
@cardEndpoint = {{baseUrl}}/graphql

###
GET  https://localhost:65203/graphql/cards?sdl

### Test Card Query Endpoint
# @ref variables
POST {{cardEndpoint}}
Content-Type: application/json

{
  test
}

### Get Card by ID - Example Card
# @ref variables
POST {{cardEndpoint}}
Content-Type: application/json

query TheQuery($cardId: String!){
  cardById(id: $cardId){
    id
  }
}

{
  "cardId":"d5c83259-9b90-47c2-b48e-c7d78519e792"
}

### Get Card with All Basic Properties
POST {{cardEndpoint}}
Content-Type: application/json

query GetCardBasicProperties($cardId: String!) {
  cardById(id: $cardId) {
    id
    oracleId
    name
    lang
    releasedAt
    uri
    scryfallUri
    layout
    highresImage
    imageStatus
    manaCost
    cmc
    typeLine
    oracleText
    reserved
    foil
    nonfoil
    oversized
    promo
    reprint
    variation
    setId
    setCode
    setName
    setType
    digital
    rarity
    artist
    illustrationId
    borderColor
    frame
    fullArt
    textless
    booster
    storySpotlight
    collectorNumber
  }
}

{
  "cardId": "d5c83259-9b90-47c2-b48e-c7d78519e792"
}

### Get Card with Image URIs
POST {{cardEndpoint}}
Content-Type: application/json

query GetCardImageUris($cardId: String!) {
  cardById(id: $cardId) {
    id
    name
    imageUris {
      small
      normal
      large
      png
      artCrop
      borderCrop
    }
  }
}

{
  "cardId": "d5c83259-9b90-47c2-b48e-c7d78519e792"
}

### Get Card with Legalities
POST {{cardEndpoint}}
Content-Type: application/json

query GetCardLegalities($cardId: String!) {
  cardById(id: $cardId) {
    id
    name
    legalities {
      standard
      modern
      legacy
      vintage
      commander
      pauper
    }
  }
}

{
  "cardId": "d5c83259-9b90-47c2-b48e-c7d78519e792"
}

### Get Card with Prices
POST {{cardEndpoint}}
Content-Type: application/json

query GetCardPrices($cardId: String!) {
  cardById(id: $cardId) {
    id
    name
    prices {
      usd
      usdFoil
      eur
      eurFoil
      tix
    }
  }
}

{
  "cardId": "d5c83259-9b90-47c2-b48e-c7d78519e792"
}

### Get Card with ALL Fields - Comprehensive Query
# @ref variables
POST {{cardEndpoint}}
Content-Type: application/json

query GetCompleteCard($cardId: String!) {
  cardById(id: $cardId) {
    id
    oracleId
    multiverseIds
    mtgoId
    mtgoFoilId
    tcgplayerId
    cardmarketId
    name
    lang
    releasedAt
    uri
    scryfallUri
    layout
    highresImage
    imageStatus
    imageUris {
      small
      normal
      large
      png
      artCrop
      borderCrop
    }
    manaCost
    cmc
    typeLine
    oracleText
    power
    toughness
    loyalty
    defense
    lifeModifier
    handModifier
    colors
    colorIdentity
    colorIndicator
    keywords
    legalities {
      standard
      future
      historic
      timeless
      gladiator
      pioneer
      explorer
      modern
      legacy
      pauper
      vintage
      penny
      commander
      oathbreaker
      standardBrawl
      brawl
      alchemy
      pauperCommander
      duel
      oldschool
      premodern
      predh
    }
    games
    reserved
    foil
    nonfoil
    finishes
    oversized
    promo
    reprint
    variation
    setId
    setCode
    setName
    setType
    setUri
    setSearchUri
    scryfallSetUri
    rulingsUri
    printsSearchUri
    collectorNumber
    digital
    rarity
    flavorText
    cardBackId
    artist
    artistIds
    illustrationId
    borderColor
    frame
    frameEffects
    securityStamp
    fullArt
    textless
    booster
    storySpotlight
    edhrecRank
    pennyRank
    prices {
      usd
      usdFoil
      usdEtched
      eur
      eurFoil
      tix
    }
    relatedUris {
      gatherer
      tcgplayerInfiniteArticles
      tcgplayerInfiniteDecks
      edhrec
    }
    purchaseUris {
      tcgplayer
      cardmarket
      cardhoarder
    }
    cardFaces {
      objectString
      name
      manaCost
      typeLine
      oracleText
      colors
      colorIndicator
      power
      toughness
      loyalty
      defense
      artist
      artistId
      illustrationId
      imageUris {
        small
        normal
        large
        png
        artCrop
        borderCrop
      }
      flavorText
      printedName
      printedTypeLine
      printedText
      watermark
      layout
      cmc
    }
    allParts {
      objectString
      id
      component
      name
      typeLine
      uri
    }
    printedName
    printedTypeLine
    printedText
    watermark
    contentWarning
    preview {
      source
      sourceUri
      previewedAt
    }
    producedMana
    attractions
  }
}

{
  "cardId": "11600105-56c6-4073-a4a6-8469030b39c9"
}

### Get Cards by Multiple IDs (Batch)
# @ref variables
POST {{cardEndpoint}}
Content-Type: application/json

query GetCardsBatch($ids: CardIdsArgEntityInput!) {
  cardsById(ids: $ids) {
    __typename
    ... on SuccessCardsResponse {
      data {
        id
        name
        manaCost
        typeLine
        oracleText
        rarity
        setName
        artist
        imageUris {
          normal
          large
        }
      }
    }
    ... on FailureResponse {
      status {
        message
      }
    }
  }
}

{
  "ids": {
    "cardIds": [
      "d5c83259-9b90-47c2-b48e-c7d78519e792",
      "11600105-56c6-4073-a4a6-8469030b39c9",
      "0000579f-7b35-4ed3-b44c-db2a538066fe"
    ]
  }
}
Content-Type: application/json


### FULL Get Cards by Multiple IDs (Batch)
# @ref variables
POST {{cardEndpoint}}
Content-Type: application/json

query GetCardsBatch($ids: CardIdsArgEntityInput!) {
  cardsById(ids: $ids) {
    __typename
    ... on SuccessCardsResponse {
      data {
    id
    oracleId
    multiverseIds
    tcgPlayerId
    cardMarketId
    name
    lang
    releasedAt
    uri
    scryfallUri
    layout
    highResImage
    imageStatus
    imageUris {
      small
      normal
      large
      png
      artCrop
      borderCrop
    }
    manaCost
    cmc
    typeLine
    oracleText
    power
    toughness
    loyalty
    defense
    lifeModifier
    handModifier
    colors
    colorIdentity
    colorIndicator
    keywords
    legalities {
      standard
      future
      historic
      timeless
      gladiator
      pioneer
      explorer
      modern
      legacy
      pauper
      vintage
      penny
      commander
      oathbreaker
      standardBrawl
      brawl
      alchemy
      pauperCommander
      duel
      oldschool
      premodern
      predh
    }
    games
    reserved
    foil
    nonFoil
    finishes
    oversized
    promo
    reprint
    variation
    setId
    setCode
    setName
    setType
    setUri
    setSearchUri
    scryfallSetUri
    rulingsUri
    printsSearchUri
    collectorNumber
    digital
    rarity
    flavorText
    cardBackId
    artist
    artistIds
    illustrationId
    borderColor
    frame
    frameEffects
    securityStamp
    fullArt
    textless
    booster
    storySpotlight
    edhRecRank
    pennyRank
    prices {
      usd
      usdFoil
      usdEtched
      eur
      eurFoil
      tix
    }
    relatedUris {
      gatherer
      tcgplayerInfiniteArticles
      tcgplayerInfiniteDecks
      edhrec
    }
    purchaseUris {
      tcgplayer
      cardmarket
      cardhoarder
    }
    cardFaces {
      objectString
      name
      manaCost
      typeLine
      oracleText
      colors
      colorIndicator
      power
      toughness
      loyalty
      defense
      artist
      artistId
      illustrationId
      imageUris {
        small
        normal
        large
        png
        artCrop
        borderCrop
      }
      flavorText
      printedName
      printedTypeLine
      printedText
      watermark
      layout
      cmc
    }
    allParts {
      objectString
      id
      component
      name
      typeLine
      uri
    }
    printedName
    printedTypeLine
    printedText
    watermark
    contentWarning
    preview {
      source
      sourceUri
      previewedAt
    }
    producedMana
    attractions
  }
    }
    ... on FailureResponse {
      status {
        message
      }
    }
  }
}

{
  "ids": {
    "cardIds": [
      "d5c83259-9b90-47c2-b48e-c7d78519e792",
      "11600105-56c6-4073-a4a6-8469030b39c9",
      "0000579f-7b35-4ed3-b44c-db2a538066fe"
    ]
  }
}