###
# Variables
# @name variables
@baseUrl = {{$dotenv BASE_URL}}
@cardEndpoint = {{baseUrl}}/graphql


### Get Cards by Name
# @ref variables
POST {{cardEndpoint}}
Content-Type: application/json

query GetCardsByName($cardName: CardNameArgEntityInput!) {
  cardsByName(cardName: $cardName) {
    __typename
    ... on SuccessCardsResponse {
      data {
        id
        name
        manaCost
        typeLine
        oracleText
        rarity
        setName
        setCode
        artist
        imageUris {
          normal
          large
        }
      }
    }
    ... on FailureResponse {
      status {
        message
      }
    }
  }
}

{
  "cardName": {
    "cardName": "Lightning Bolt"
  }
}