<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\common\Lib.Shared.DataModels\Lib.Shared.DataModels.csproj" />
    <ProjectReference Include="..\..\common\Lib.Shared.Invocation\Lib.Shared.Invocation.csproj" />
    <ProjectReference Include="..\..\Lib.Adapters\Lib.Adapter.UserCards\Lib.Adapter.UserCards.csproj" />
    <ProjectReference Include="..\..\Lib.Adapters\Lib.Adapter.UserSetCards\Lib.Adapter.UserSetCards.csproj" />
  </ItemGroup>

</Project>