###
# Add Set Group To User Set Card Mutation
# Frontend: client/src/graphql/queries/userCards.ts - ADD_SET_GROUP_TO_USER_SET_CARD
# NOTE: This mutation requires JWT authentication header
###
@baseUrl = https://localhost:65203
@gqlEndpoint = {{baseUrl}}/graphql


### Add Set Group to User Set Card
POST {{gqlEndpoint}}
Content-Type: application/json
Authorization: Bearer {{BEARER_TOKEN}}

mutation AddSetGroupToUserSetCard($input: AddSetGroupToUserSetCardInput!) {
  addSetGroupToUserSetCard(input: $input) {
    __typename
    ... on UserSetCardSuccessResponse {
      data {
        userId
        setId
        totalCards
        uniqueCards
        collecting {
          setGroupId
          collecting
          counts {
            total
            nonFoil
            foil
            etched
          }
          collectingFinishes
        }
      }
      status {
        message
        statusCode
      }
    }
    ... on FailureResponse {
      status {
        message
        statusCode
      }
    }
  }
}

{
  "input": {
    "setId": "30ec97cb-dca9-4bf4-a98b-310f9d8ceaff",
    "setGroupId": "booster",
    "collecting": true,
    "counts": {
      "total": 602,
      "nonFoil": 301,
      "foil": 301,
      "etched": 0
    },
    "collectingFinishes": ["nonFoil", "foil"]
  }
}
